
# Command to start on workspace startup
tasks:
  - init: >
      setup/wagtail.sh && setup/frontend.sh
  - command: >
      python manage.py runserver 0.0.0.0:8000
    name: python
  - openMode: split-right
  - command: >
      cd frontend && npm run gulp watch
    name: node
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
  - port: 3000
    onOpen: open-preview
github:
    prebuilds:
        pullRequestsFromForks: true
