
# Command to start on workspace startup
tasks:
  - command: >
      setup/wagtail.sh && python manage.py runserver 0.0.0.0:8000
    name: python
  - command: >
      setup/frontend.sh && cd frontend && npm run gulp watch
    name: node
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview
  - port: 3000